export const SALES_ERROR_CODES = {
  NOT_FOUND: 'SAL.NOT_FOUND',
  INVALID_STATUS: 'SAL.INVALID_STATUS',
  VERSION_CONFLICT: 'SAL.VERSION_CONFLICT',
  CUSTOMER_BLOCKED: 'SAL.CUSTOMER_BLOCKED',
  CUSTOMER_NOT_FOUND: 'SAL.CUSTOMER_NOT_FOUND',
  PRODUCT_NOT_FOUND: 'SAL.PRODUCT_NOT_FOUND',
  WAREHOUSE_NOT_FOUND: 'SAL.WAREHOUSE_NOT_FOUND',
  EMPTY_LINES: 'SAL.EMPTY_LINES',
  INVALID_LINE: 'SAL.INVALID_LINE',
  STOCK_RESERVE_FAILED: 'SAL.STOCK_RESERVE_FAILED',
  CREDIT_DENIED: 'SAL.CREDIT_DENIED',
} as const;

export type SalesErrorCode =
  (typeof SALES_ERROR_CODES)[keyof typeof SALES_ERROR_CODES];

export const SALES_EVENT_TYPES = {
  CREATED: 'sales.order.created.v1',
  CONFIRMED: 'sales.order.confirmed.v1',
  CANCELLED: 'sales.order.cancelled.v1',
} as const;

export const SALES_RESERVE_REF_TYPE = 'sales.order';
