export const HR_ERROR_CODES = {
  NOT_FOUND: 'HR.NOT_FOUND',
  EMPLOYEE_NOT_FOUND: 'HR.EMPLOYEE_NOT_FOUND',
  CONTRACT_NOT_FOUND: 'HR.CONTRACT_NOT_FOUND',
  MATRICULE_EXISTS: 'HR.MATRICULE_EXISTS',
  INVALID_STATUS: 'HR.INVALID_STATUS',
  INVALID_DATES: 'HR.INVALID_DATES',
  CNSS_INVALID_PERIOD: 'HR.CNSS_INVALID_PERIOD',
  CNSS_RATES_PENDING: 'HR.CNSS_RATES_PENDING',
  CNSS_SNAPSHOT_EXISTS: 'HR.CNSS_SNAPSHOT_EXISTS',
  IRPP_INVALID_PERIOD: 'HR.IRPP_INVALID_PERIOD',
  IRPP_INVALID_BRACKETS: 'HR.IRPP_INVALID_BRACKETS',
  IRPP_RATES_PENDING: 'HR.IRPP_RATES_PENDING',
  IRPP_SNAPSHOT_EXISTS: 'HR.IRPP_SNAPSHOT_EXISTS',
  BULLETIN_INVALID_PERIOD: 'HR.BULLETIN_INVALID_PERIOD',
  BULLETIN_SNAPSHOTS_PENDING: 'HR.BULLETIN_SNAPSHOTS_PENDING',
  BULLETIN_EXISTS: 'HR.BULLETIN_EXISTS',
  BULLETIN_NOT_FOUND: 'HR.BULLETIN_NOT_FOUND',
} as const;

export type HrErrorCode = (typeof HR_ERROR_CODES)[keyof typeof HR_ERROR_CODES];

export const HR_EVENT_TYPES = {
  EMPLOYEE_CREATED: 'hr.employee.created.v1',
  EMPLOYEE_UPDATED: 'hr.employee.updated.v1',
  CONTRACT_CREATED: 'hr.contract.created.v1',
  CONTRACT_ENDED: 'hr.contract.ended.v1',
  CNSS_SNAPSHOT_CREATED: 'hr.cnss_snapshot.created.v1',
  IRPP_BRACKETS_REPLACED: 'hr.irpp_brackets.replaced.v1',
  IRPP_SNAPSHOT_CREATED: 'hr.irpp_snapshot.created.v1',
  BULLETIN_CREATED: 'hr.bulletin.created.v1',
} as const;
