export const HR_ERROR_CODES = {
  NOT_FOUND: 'HR.NOT_FOUND',
  EMPLOYEE_NOT_FOUND: 'HR.EMPLOYEE_NOT_FOUND',
  CONTRACT_NOT_FOUND: 'HR.CONTRACT_NOT_FOUND',
  MATRICULE_EXISTS: 'HR.MATRICULE_EXISTS',
  JOB_TITLE_NOT_FOUND: 'HR.JOB_TITLE_NOT_FOUND',
  JOB_TITLE_CODE_EXISTS: 'HR.JOB_TITLE_CODE_EXISTS',
  JOB_TITLE_INVALID_CODE: 'HR.JOB_TITLE_INVALID_CODE',
  JOB_TITLE_INACTIVE: 'HR.JOB_TITLE_INACTIVE',
  DOCUMENT_NOT_FOUND: 'HR.DOCUMENT_NOT_FOUND',
  INVALID_STATUS: 'HR.INVALID_STATUS',
  INVALID_DATES: 'HR.INVALID_DATES',
  CNSS_INVALID_PERIOD: 'HR.CNSS_INVALID_PERIOD',
  CNSS_RATES_PENDING: 'HR.CNSS_RATES_PENDING',
  CNSS_SNAPSHOT_EXISTS: 'HR.CNSS_SNAPSHOT_EXISTS',
  IRPP_INVALID_PERIOD: 'HR.IRPP_INVALID_PERIOD',
  IRPP_INVALID_BRACKETS: 'HR.IRPP_INVALID_BRACKETS',
  IRPP_RATES_PENDING: 'HR.IRPP_RATES_PENDING',
  IRPP_SNAPSHOT_EXISTS: 'HR.IRPP_SNAPSHOT_EXISTS',
  BULLETIN_INVALID_PERIOD: 'HR.BULLETIN_INVALID_PERIOD',
  BULLETIN_SNAPSHOTS_PENDING: 'HR.BULLETIN_SNAPSHOTS_PENDING',
  BULLETIN_EXISTS: 'HR.BULLETIN_EXISTS',
  BULLETIN_NOT_FOUND: 'HR.BULLETIN_NOT_FOUND',
  BULLETIN_PDF_UNAVAILABLE: 'HR.BULLETIN_PDF_UNAVAILABLE',
  PHOTO_INVALID: 'HR.PHOTO_INVALID',
  USER_INVALID: 'HR.USER_INVALID',
  USER_ALREADY_LINKED: 'HR.USER_ALREADY_LINKED',
  SITE_INVALID: 'HR.SITE_INVALID',
  DOC_KIND_NOT_FOUND: 'HR.DOC_KIND_NOT_FOUND',
  DOC_KIND_CODE_EXISTS: 'HR.DOC_KIND_CODE_EXISTS',
  DOC_KIND_INVALID_CODE: 'HR.DOC_KIND_INVALID_CODE',
  DOC_KIND_INACTIVE: 'HR.DOC_KIND_INACTIVE',
  CONTRACT_PDF_UNAVAILABLE: 'HR.CONTRACT_PDF_UNAVAILABLE',
  CIN_INVALID: 'HR.CIN_INVALID',
  PRINT_TEMPLATE_NOT_FOUND: 'HR.PRINT_TEMPLATE_NOT_FOUND',
  PRINT_TEMPLATE_CODE_EXISTS: 'HR.PRINT_TEMPLATE_CODE_EXISTS',
  PRINT_TEMPLATE_INVALID_CODE: 'HR.PRINT_TEMPLATE_INVALID_CODE',
  ATTESTATION_REQUIRES_ACTIVE_CONTRACT: 'HR.ATTESTATION_REQUIRES_ACTIVE_CONTRACT',
  ATTESTATION_PDF_UNAVAILABLE: 'HR.ATTESTATION_PDF_UNAVAILABLE',
} as const;

export type HrErrorCode = (typeof HR_ERROR_CODES)[keyof typeof HR_ERROR_CODES];

export const HR_IMAGE_MIMES = [
  'image/jpeg',
  'image/png',
  'image/webp',
  'image/gif',
] as const;

export function isHrImageMime(mime: string | undefined | null): boolean {
  if (!mime) return false;
  return (HR_IMAGE_MIMES as readonly string[]).includes(mime.toLowerCase());
}

export function isHrPreviewableMime(mime: string | undefined | null): boolean {
  if (!mime) return false;
  const m = mime.toLowerCase();
  return isHrImageMime(m) || m === 'application/pdf';
}

export const HR_EVENT_TYPES = {
  EMPLOYEE_CREATED: 'hr.employee.created.v1',
  EMPLOYEE_UPDATED: 'hr.employee.updated.v1',
  CONTRACT_CREATED: 'hr.contract.created.v1',
  CONTRACT_ENDED: 'hr.contract.ended.v1',
  CONTRACT_PDF_GENERATED: 'hr.contract.pdf_generated.v1',
  ATTESTATION_PDF_GENERATED: 'hr.attestation.pdf_generated.v1',
  PRINT_TEMPLATE_CREATED: 'hr.print_template.created.v1',
  PRINT_TEMPLATE_UPDATED: 'hr.print_template.updated.v1',
  CNSS_SNAPSHOT_CREATED: 'hr.cnss_snapshot.created.v1',
  IRPP_BRACKETS_REPLACED: 'hr.irpp_brackets.replaced.v1',
  IRPP_SNAPSHOT_CREATED: 'hr.irpp_snapshot.created.v1',
  BULLETIN_CREATED: 'hr.bulletin.created.v1',
  BULLETIN_PDF_GENERATED: 'hr.bulletin.pdf_generated.v1',
  JOB_TITLE_CREATED: 'hr.job_title.created.v1',
  JOB_TITLE_UPDATED: 'hr.job_title.updated.v1',
  DOC_KIND_CREATED: 'hr.doc_kind.created.v1',
  DOC_KIND_UPDATED: 'hr.doc_kind.updated.v1',
  EMPLOYEE_DOCUMENT_ATTACHED: 'hr.employee.document.attached.v1',
} as const;
