-- D290 — production need hint (ASSISTED only; no auto WO)
ALTER TYPE "AtmTriggerKind" ADD VALUE IF NOT EXISTS 'SALES_ORDER_CONFIRMED';
ALTER TYPE "AtmActionKind" ADD VALUE IF NOT EXISTS 'PRODUCTION_NEED_HINT';
