import type { ModuleManifest } from '../manifest.types';

/**
 * Backup & Recovery — domain owner (D304–D313 specific folders).
 */
export const backupManifest: ModuleManifest = {
  id: 'backup',
  name: 'Sauvegarde',
  version: '1.3.0',
  apiVersion: '1',
  description:
    'Politiques et artefacts AUTHORITY — CONFIGURATION / DATABASE / SPECIFIC_FOLDERS (D313)',
  capabilities: [
    {
      key: 'backup.dashboard.read',
      moduleId: 'backup',
      version: '1',
      description: 'Read backup dashboard counts',
      permissionKey: 'backup.view',
      riskLevel: 'low',
    },
    {
      key: 'backup.create',
      moduleId: 'backup',
      version: '1',
      description: 'Create configuration or database backup',
      permissionKey: 'backup.create',
      riskLevel: 'high',
      requiresAudit: true,
      requiresIdempotency: true,
    },
    {
      key: 'backup.specific_folder.create',
      moduleId: 'backup',
      version: '1',
      description:
        'Create streaming ZIP of company-sandbox folders (LOCAL_DISK / DOWNLOAD)',
      permissionKey: 'backup.specific_folder.create',
      riskLevel: 'high',
      requiresAudit: true,
      requiresIdempotency: true,
    },
    {
      key: 'backup.verify',
      moduleId: 'backup',
      version: '1',
      description: 'Verify backup artifact checksum',
      permissionKey: 'backup.verify',
      riskLevel: 'medium',
      requiresAudit: true,
    },
    {
      key: 'backup.restore',
      moduleId: 'backup',
      version: '1',
      description:
        'Request/approve/apply restore (dual-control + reauth; logical company apply; cluster pg_restore blocked)',
      permissionKey: 'backup.restore',
      riskLevel: 'high',
      requiresAudit: true,
      requiresIdempotency: true,
    },
    {
      key: 'backup.manage_settings',
      moduleId: 'backup',
      version: '1',
      description: 'Manage backup policies / destinations settings',
      permissionKey: 'backup.manage_settings',
      riskLevel: 'high',
      requiresAudit: true,
    },
  ],
  commands: [
    'backup.create',
    'backup.verify',
    'backup.lock',
    'backup.delete',
    'backup.restore.request',
    'backup.restore.approve',
    'backup.restore.apply',
    'backup.retention.run',
    'backup.specificFolders.create',
    'backup.companyFiles.mkdir',
    'backup.localDisk.mkdir',
  ],
  queries: [
    'backup.dashboard',
    'backup.list',
    'backup.get',
    'backup.jobs.list',
    'backup.destinations.list',
    'backup.destinations.local.resolve',
    'backup.policies.list',
    'backup.restore_requests.list',
    'backup.specificFolders.config',
    'backup.specificFolders.roots',
    'backup.companyFiles.list',
  ],
  permissions: [
    'backup.view',
    'backup.create',
    'backup.verify',
    'backup.restore',
    'backup.manage_settings',
    'backup.specific_folder.view',
    'backup.specific_folder.create',
    'backup.specific_folder.configure',
    'backup.destination.download',
    'backup.destination.local_disk',
  ],
  publishedEvents: [
    'backup.requested.v1',
    'backup.completed.v1',
    'backup.failed.v1',
    'backup.restore.requested.v1',
    'backup.restore.authorized.v1',
    'backup.restore.started.v1',
    'backup.restore.completed.v1',
    'backup.restore.failed.v1',
    'backup.retention.completed.v1',
    'backup.specific_folders.completed.v1',
  ],
  consumedEvents: [],
  dependencies: ['platform', 'organization', 'settings'],
  healthChecks: ['backup.kernel'],
  navigationEntries: [
    {
      id: 'backup-home',
      label: 'Sauvegardes',
      href: '/backup',
    },
  ],
  settingsDefinitions: [
    { key: 'backup.enabled', scope: 'company' },
    { key: 'backup.defaultType', scope: 'company' },
    { key: 'backup.preActionSnapshot.enabled', scope: 'company' },
    { key: 'backup.destination.primary', scope: 'company' },
    { key: 'backup.restore.requireElevatedPermission', scope: 'company' },
    { key: 'backup.retention.enabled', scope: 'company' },
    { key: 'backup.retention.keepDays', scope: 'company' },
    { key: 'backup.retention.lockedNeverDelete', scope: 'company' },
    { key: 'backup.schedule.enabled', scope: 'company' },
    { key: 'backup.schedule.hourTunis', scope: 'company' },
    { key: 'backup.restore.safetyBackup.required', scope: 'company' },
    { key: 'backup.autoBackup.enabled', scope: 'company' },
    { key: 'backup.autoBackup.hourTunis', scope: 'company' },
    { key: 'backup.autoBackup.scope', scope: 'company' },
    { key: 'backup.specificFolders.enabled', scope: 'company' },
    { key: 'backup.specificFolders.defaultSelection', scope: 'company' },
    { key: 'backup.specificFolders.allowUserSelection', scope: 'company' },
    { key: 'backup.specificFolders.followSymlinks', scope: 'company' },
    { key: 'backup.specificFolders.includePatterns', scope: 'company' },
    { key: 'backup.specificFolders.excludePatterns', scope: 'company' },
    { key: 'backup.specificFolders.maxSize', scope: 'company' },
    { key: 'backup.specificFolders.verifyAfterBackup', scope: 'company' },
    { key: 'backup.specificFolders.auto.enabled', scope: 'company' },
    { key: 'backup.specificFolders.auto.hourTunis', scope: 'company' },
    { key: 'backup.destination.allowDownload', scope: 'company' },
    { key: 'backup.destination.allowLocalDisk', scope: 'company' },
    { key: 'backup.destination.localSubpath', scope: 'company' },
    { key: 'backup.destination.allowExternalDisk', scope: 'company' },
    { key: 'backup.destination.allowNAS', scope: 'company' },
    { key: 'backup.destination.allowNetworkShare', scope: 'company' },
    { key: 'backup.destination.allowObjectStorage', scope: 'company' },
    { key: 'backup.destination.allowRemoteServer', scope: 'company' },
  ],
};
