import type { ModuleManifest } from '../manifest.types';

export const financeManifest: ModuleManifest = {
  id: 'finance',
  name: 'Finance',
  version: '1.1.0',
  apiVersion: '1',
  description:
    'Finance AR/AP — invoices, receipts, AP disbursements, bank soft recon',
  capabilities: [
    {
      key: 'finance.ar.read',
      moduleId: 'finance',
      version: '1',
      description:
        'List and read AR invoices / open items / payments / AP disbursements / bank lines',
      permissionKey: 'finance.ar.read',
      riskLevel: 'low',
    },
    {
      key: 'finance.ar.write',
      moduleId: 'finance',
      version: '1',
      description:
        'Create / issue AR invoices, open items, bank accounts and statement lines',
      permissionKey: 'finance.ar.write',
      riskLevel: 'medium',
      requiresAudit: true,
    },
    {
      key: 'finance.allocate',
      moduleId: 'finance',
      version: '1',
      description:
        'Record AR/AP payments, allocate, instruments, bank match/unmatch (no GL on match)',
      permissionKey: 'finance.allocate',
      riskLevel: 'high',
      requiresAudit: true,
    },
  ],
  commands: [
    'finance.open_item.create',
    'finance.open_item.allocate',
    'finance.invoice.create',
    'finance.invoice.issue',
    'finance.invoice.cancel',
    'finance.credit_note.create',
    'finance.credit_note.issue',
    'finance.credit_note.cancel',
    'finance.payment.create',
    'finance.ap_payment.create',
    'finance.ap_bill.create',
    'finance.ap_bill.post',
    'finance.ap_bill.cancel',
    'finance.payment.allocate',
    'finance.payment.reverse',
    'finance.instrument.transition',
    'finance.bank.account.create',
    'finance.bank.line.create',
    'finance.bank.match',
    'finance.bank.unmatch',
    'finance.bank.fee_post',
    'finance.dunning.prepare',
    'finance.dunning.confirm',
    'finance.dunning.send',
    'finance.dunning.wa_webhook',
    'finance.payment_declaration.acknowledge',
    'finance.payment_declaration.reject',
  ],
  queries: [
    'finance.open_items.list',
    'finance.open_items.get',
    'finance.invoices.list',
    'finance.credit_notes.list',
    'finance.payments.list',
    'finance.ap_payments.list',
    'finance.ap_bills.list',
    'finance.ap_bills.get',
    'finance.instruments.list',
    'finance.promises.list',
    'finance.payment_declarations.list',
    'finance.payment_declarations.get',
    'finance.credit.snapshot',
    'finance.bank.accounts.list',
    'finance.bank.lines.list',
    'finance.dunning.preview',
    'finance.dunning.list',
  ],
  permissions: [
    'finance.ar.read',
    'finance.ar.write',
    'finance.allocate',
  ],
  dependencies: [
    'platform',
    'organization',
    'customers',
    'tax',
  ],
  publishedEvents: [
    'finance.open_item.created.v1',
    'finance.allocation.recorded.v1',
    'finance.invoice.issued.v1',
    'finance.invoice.cancelled.v1',
    'finance.credit_note.issued.v1',
    'finance.payment.posted.v1',
    'finance.payment.allocated.v1',
    'finance.payment.reversed.v1',
    'finance.instrument.status.v1',
    'finance.instrument.rejected.v1',
    'finance.promise.created.v1',
    'finance.promise.status.v1',
    'finance.bank.matched.v1',
    'finance.bank.unmatched.v1',
    'finance.bank.ignored.v1',
    'finance.bank.unignored.v1',
    'finance.bank.fee_posted.v1',
    'finance.ap_payment.posted.v1',
    'finance.ap_bill.created.v1',
    'finance.ap_bill.posted.v1',
    'finance.ap_bill.cancelled.v1',
    'finance.payment_declaration.acknowledged.v1',
    'finance.payment_declaration.rejected.v1',
    'finance.dunning.prepared.v1',
    'finance.dunning.confirmed.v1',
    'finance.dunning.sent.v1',
    'finance.dunning.send_failed.v1',
    'finance.dunning.wa_status.v1',
  ],
  consumedEvents: [
    'delivery.shipment.delivered.v1',
    'portals.payment_declaration.submitted.v1',
    'portals.payment_declaration.cancelled.v1',
  ],
  navigationEntries: [
    { id: 'open-items', label: 'Créances', href: '/finance' },
    { id: 'invoices', label: 'Factures', href: '/finance/invoices' },
    { id: 'credit-notes', label: 'Avoirs', href: '/finance/credit-notes' },
    { id: 'payments', label: 'Encaissements', href: '/finance/payments' },
    {
      id: 'payment-declarations',
      label: 'Déclarations portail',
      href: '/finance/payment-declarations',
    },
    { id: 'instruments', label: 'Instruments', href: '/finance/instruments' },
    { id: 'promises', label: 'Promesses', href: '/finance/promises' },
    { id: 'banking', label: 'Banque', href: '/finance/banking' },
    { id: 'ap-bills', label: 'Factures fournisseurs', href: '/finance/ap-bills' },
  ],
};
