import type { ModuleManifest } from '../manifest.types';

export const financeManifest: ModuleManifest = {
  id: 'finance',
  name: 'Finance',
  version: '1.1.0',
  apiVersion: '1',
  description:
    'Finance AR — invoices, payments, instruments, promises, bank soft recon',
  capabilities: [
    {
      key: 'finance.ar.read',
      moduleId: 'finance',
      version: '1',
      description:
        'List and read AR invoices / open items / payments / credit / bank lines',
      permissionKey: 'finance.ar.read',
      riskLevel: 'low',
    },
    {
      key: 'finance.ar.write',
      moduleId: 'finance',
      version: '1',
      description:
        'Create / issue AR invoices, open items, bank accounts and statement lines',
      permissionKey: 'finance.ar.write',
      riskLevel: 'medium',
      requiresAudit: true,
    },
    {
      key: 'finance.allocate',
      moduleId: 'finance',
      version: '1',
      description:
        'Record payments, allocate, instruments, bank match/unmatch (no GL on match)',
      permissionKey: 'finance.allocate',
      riskLevel: 'high',
      requiresAudit: true,
    },
  ],
  commands: [
    'finance.open_item.create',
    'finance.open_item.allocate',
    'finance.invoice.create',
    'finance.invoice.issue',
    'finance.invoice.cancel',
    'finance.payment.create',
    'finance.payment.allocate',
    'finance.payment.reverse',
    'finance.instrument.transition',
    'finance.bank.account.create',
    'finance.bank.line.create',
    'finance.bank.match',
    'finance.bank.unmatch',
    'finance.dunning.prepare',
    'finance.dunning.confirm',
  ],
  queries: [
    'finance.open_items.list',
    'finance.open_items.get',
    'finance.invoices.list',
    'finance.payments.list',
    'finance.instruments.list',
    'finance.credit.snapshot',
    'finance.bank.accounts.list',
    'finance.bank.lines.list',
    'finance.dunning.preview',
    'finance.dunning.list',
  ],
  permissions: [
    'finance.ar.read',
    'finance.ar.write',
    'finance.allocate',
  ],
  dependencies: [
    'platform',
    'organization',
    'customers',
    'tax',
  ],
  publishedEvents: [
    'finance.open_item.created.v1',
    'finance.allocation.recorded.v1',
    'finance.invoice.issued.v1',
    'finance.invoice.cancelled.v1',
    'finance.payment.posted.v1',
    'finance.payment.allocated.v1',
    'finance.payment.reversed.v1',
    'finance.instrument.status.v1',
    'finance.instrument.rejected.v1',
    'finance.promise.created.v1',
    'finance.promise.status.v1',
    'finance.bank.matched.v1',
    'finance.bank.unmatched.v1',
    'finance.bank.ignored.v1',
    'finance.bank.unignored.v1',
    'finance.dunning.prepared.v1',
    'finance.dunning.confirmed.v1',
  ],
  consumedEvents: ['delivery.shipment.delivered.v1'],
  navigationEntries: [
    { id: 'open-items', label: 'Créances', href: '/finance' },
    { id: 'invoices', label: 'Factures', href: '/finance/invoices' },
    { id: 'payments', label: 'Encaissements', href: '/finance/payments' },
    { id: 'instruments', label: 'Instruments', href: '/finance/instruments' },
    { id: 'promises', label: 'Promesses', href: '/finance/promises' },
    { id: 'banking', label: 'Banque', href: '/finance/banking' },
  ],
};
