import type { ModuleManifest } from '../manifest.types';

/**
 * HR light + job titles/docs (D209) + CNSS/IRPP V0.
 * Rates & brackets only from VALIDATED Prefs / human tables — never invent.
 */
export const hrManifest: ModuleManifest = {
  id: 'hr',
  name: 'Ressources humaines',
  version: '1.3.0',
  apiVersion: '1',
  description:
    'HR — employees, job titles, contracts, dossier docs, CNSS/IRPP from VALIDATED Prefs',
  capabilities: [
    {
      key: 'hr.employee.read',
      moduleId: 'hr',
      version: '1',
      description: 'List and view employees and contracts',
      permissionKey: 'hr.employee.read',
      riskLevel: 'low',
    },
    {
      key: 'hr.employee.write',
      moduleId: 'hr',
      version: '1',
      description: 'Create/update employees and contracts',
      permissionKey: 'hr.employee.write',
      riskLevel: 'medium',
      requiresAudit: true,
    },
    {
      key: 'hr.wage.read',
      moduleId: 'hr',
      version: '1',
      description: 'Reveal wage fields and CNSS/IRPP amounts (field ACL)',
      permissionKey: 'hr.wage.read',
      riskLevel: 'high',
    },
  ],
  commands: [
    'hr.employee.create',
    'hr.employee.patch',
    'hr.contract.create',
    'hr.contract.patch',
    'hr.contract.end',
    'hr.cnss.snapshot.create',
    'hr.irpp.brackets.replace',
    'hr.irpp.snapshot.create',
    'hr.bulletin.create',
    'hr.job_title.create',
    'hr.job_title.patch',
    'hr.employee.document.upload',
  ],
  queries: [
    'hr.employees.list',
    'hr.employee.get',
    'hr.job_titles.list',
    'hr.employee.documents.list',
    'hr.employee.document.download',
    'hr.cnss.preview',
    'hr.cnss.snapshots.list',
    'hr.irpp.brackets.list',
    'hr.irpp.preview',
    'hr.irpp.snapshots.list',
    'hr.bulletin.preview',
    'hr.bulletins.list',
    'hr.bulletin.get',
  ],
  permissions: ['hr.employee.read', 'hr.employee.write', 'hr.wage.read'],
  dependencies: ['platform', 'organization', 'identity'],
  publishedEvents: [
    'hr.employee.created.v1',
    'hr.employee.updated.v1',
    'hr.contract.created.v1',
    'hr.contract.ended.v1',
    'hr.cnss_snapshot.created.v1',
    'hr.irpp_brackets.replaced.v1',
    'hr.irpp_snapshot.created.v1',
    'hr.bulletin.created.v1',
    'hr.job_title.created.v1',
    'hr.job_title.updated.v1',
    'hr.employee.document.attached.v1',
  ],
  navigationEntries: [
    { id: 'hr-employees', label: 'Employés', href: '/hr' },
    { id: 'hr-job-titles', label: 'Postes', href: '/hr?tab=postes' },
    { id: 'hr-bulletins', label: 'Bulletins', href: '/hr?tab=bulletins' },
  ],
};
