import type { ModuleManifest } from '../manifest.types';

export const portalsManifest: ModuleManifest = {
  id: 'portals',
  name: 'Portals',
  version: '0.7.0',
  apiVersion: '1',
  description:
    'External portals — Customer Portal P1–P7 + P6b documents signed download',
  capabilities: [
    {
      key: 'customer_portal.access',
      moduleId: 'portals',
      version: '1',
      description: 'Access customer portal login and session',
      permissionKey: 'customer_portal.access',
      riskLevel: 'medium',
    },
    {
      key: 'customer_portal.dashboard.read',
      moduleId: 'portals',
      version: '1',
      description: 'Read customer portal dashboard shell',
      permissionKey: 'customer_portal.dashboard.read',
      riskLevel: 'low',
    },
    {
      key: 'customer_portal.claims.read',
      moduleId: 'portals',
      version: '1',
      description: 'List and read portal claims for membership customer',
      permissionKey: 'customer_portal.claims.read',
      riskLevel: 'low',
    },
    {
      key: 'customer_portal.claims.create',
      moduleId: 'portals',
      version: '1',
      description: 'Create portal claims linked to own orders/shipments',
      permissionKey: 'customer_portal.claims.create',
      riskLevel: 'medium',
      requiresAudit: true,
    },
    {
      key: 'customer_portal.documents.read',
      moduleId: 'portals',
      version: '1',
      description: 'List and download CUSTOMER_PORTAL documents for membership',
      permissionKey: 'customer_portal.documents.read',
      riskLevel: 'low',
    },
  ],
  commands: ['customer_portal.claims.create'],
  queries: [
    'customer_portal.me',
    'customer_portal.dashboard',
    'customer_portal.claims.list',
    'customer_portal.claims.get',
    'customer_portal.documents.list',
    'customer_portal.documents.download',
  ],
  permissions: [
    'customer_portal.access',
    'customer_portal.dashboard.read',
    'customer_portal.claims.read',
    'customer_portal.claims.create',
    'customer_portal.documents.read',
  ],
  dependencies: [
    'platform',
    'identity',
    'customers',
    'sales',
    'delivery',
    'finance',
    'documents',
  ],
  publishedEvents: ['portals.claim.created.v1'],
  navigationEntries: [],
};
