import type { ModuleManifest } from '../manifest.types';

export const portalsManifest: ModuleManifest = {
  id: 'portals',
  name: 'Portals',
  version: '0.8.0',
  apiVersion: '1',
  description:
    'External portals — Customer Portal + Employee Portal leave + bulletins (D221)',
  capabilities: [
    {
      key: 'customer_portal.access',
      moduleId: 'portals',
      version: '1',
      description: 'Access customer portal login and session',
      permissionKey: 'customer_portal.access',
      riskLevel: 'medium',
    },
    {
      key: 'customer_portal.dashboard.read',
      moduleId: 'portals',
      version: '1',
      description: 'Read customer portal dashboard shell',
      permissionKey: 'customer_portal.dashboard.read',
      riskLevel: 'low',
    },
    {
      key: 'customer_portal.claims.read',
      moduleId: 'portals',
      version: '1',
      description: 'List and read portal claims for membership customer',
      permissionKey: 'customer_portal.claims.read',
      riskLevel: 'low',
    },
    {
      key: 'customer_portal.claims.create',
      moduleId: 'portals',
      version: '1',
      description: 'Create portal claims linked to own orders/shipments',
      permissionKey: 'customer_portal.claims.create',
      riskLevel: 'medium',
      requiresAudit: true,
    },
    {
      key: 'customer_portal.documents.read',
      moduleId: 'portals',
      version: '1',
      description: 'List and download CUSTOMER_PORTAL documents for membership',
      permissionKey: 'customer_portal.documents.read',
      riskLevel: 'low',
    },
    {
      key: 'employee_portal.access',
      moduleId: 'portals',
      version: '1',
      description:
        'Access employee portal login, leave, calendar, and own bulletins',
      permissionKey: 'employee_portal.access',
      riskLevel: 'medium',
    },
  ],
  commands: [
    'customer_portal.claims.create',
    'customer_portal.payment_declarations.create',
    'customer_portal.payment_declarations.cancel',
    'employee_portal.absence.create',
  ],
  queries: [
    'customer_portal.me',
    'customer_portal.dashboard',
    'customer_portal.claims.list',
    'customer_portal.claims.get',
    'customer_portal.payment_declarations.list',
    'customer_portal.payment_declarations.get',
    'customer_portal.documents.list',
    'customer_portal.documents.download',
    'employee_portal.me',
    'employee_portal.absences.list',
    'employee_portal.calendar.get',
    'employee_portal.bulletins.list',
    'employee_portal.bulletins.get',
    'employee_portal.bulletins.pdf',
  ],
  permissions: [
    'customer_portal.access',
    'customer_portal.dashboard.read',
    'customer_portal.claims.read',
    'customer_portal.claims.create',
    'customer_portal.payment_declarations.read',
    'customer_portal.payment_declarations.create',
    'customer_portal.documents.read',
    'employee_portal.access',
  ],
  dependencies: [
    'platform',
    'identity',
    'organization',
    'hr',
    'attendance',
    'customers',
    'sales',
    'delivery',
    'finance',
    'documents',
  ],
  publishedEvents: [
    'portals.claim.created.v1',
    'portals.payment_declaration.submitted.v1',
    'portals.payment_declaration.cancelled.v1',
  ],
  navigationEntries: [],
};
