import type { ModuleManifest } from '../manifest.types';

export const productionManifest: ModuleManifest = {
  id: 'production',
  name: 'Production',
  version: '1.1.0',
  apiVersion: '1',
  description:
    'Production light — work orders, declare, scrap · digital worksheet Prep→Weigh→Control (D292)',
  capabilities: [
    {
      key: 'production.read',
      moduleId: 'production',
      version: '1',
      description: 'List and view work orders and worksheets',
      permissionKey: 'production.read',
      riskLevel: 'low',
    },
    {
      key: 'production.wo.write',
      moduleId: 'production',
      version: '1',
      description: 'Create/release work orders and worksheet Prep/Weigh/Control',
      permissionKey: 'production.wo.write',
      riskLevel: 'medium',
      requiresAudit: true,
      requiresIdempotency: true,
    },
    {
      key: 'production.declare',
      moduleId: 'production',
      version: '1',
      description: 'Declare consumption and output',
      permissionKey: 'production.declare',
      riskLevel: 'high',
      requiresAudit: true,
      requiresIdempotency: true,
    },
    {
      key: 'production.scrap',
      moduleId: 'production',
      version: '1',
      description: 'Record scrap on declare',
      permissionKey: 'production.scrap',
      riskLevel: 'medium',
      requiresAudit: true,
    },
  ],
  commands: [
    'production.work_order.create',
    'production.work_order.release',
    'production.work_order.declare',
    'production.worksheet.create',
    'production.worksheet.prepare',
    'production.worksheet.weigh',
    'production.worksheet.control',
  ],
  queries: [
    'production.work_orders.list',
    'production.work_order.get',
    'production.worksheets.list',
    'production.worksheet.get',
  ],
  permissions: [
    'production.read',
    'production.wo.write',
    'production.declare',
    'production.scrap',
  ],
  dependencies: ['platform', 'organization', 'inventory', 'products'],
  publishedEvents: [
    'production.work_order.created.v1',
    'production.work_order.released.v1',
    'production.consumption.posted.v1',
    'production.output.posted.v1',
    'production.yield.deviation.v1',
    'production.scrap.posted.v1',
    'production.worksheet.created.v1',
    'production.worksheet.prepared.v1',
    'production.worksheet.weighed.v1',
    'production.worksheet.controlled.v1',
    'production.worksheet.rejected.v1',
    'production.worksheet.cancelled.v1',
  ],
  consumedEvents: [],
  navigationEntries: [
    { id: 'of', label: 'Ordres de fabrication', href: '/production' },
    {
      id: 'worksheet',
      label: 'Fiches digitales',
      href: '/production/worksheets',
    },
  ],
};
