import type { ModuleManifest } from '../manifest.types';

export const productionManifest: ModuleManifest = {
  id: 'production',
  name: 'Production',
  version: '1.0.0',
  apiVersion: '1',
  description: 'Production light — work orders, declare, scrap',
  capabilities: [
    {
      key: 'production.read',
      moduleId: 'production',
      version: '1',
      description: 'List and view work orders',
      permissionKey: 'production.read',
      riskLevel: 'low',
    },
    {
      key: 'production.wo.write',
      moduleId: 'production',
      version: '1',
      description: 'Create and release work orders',
      permissionKey: 'production.wo.write',
      riskLevel: 'medium',
      requiresAudit: true,
      requiresIdempotency: true,
    },
    {
      key: 'production.declare',
      moduleId: 'production',
      version: '1',
      description: 'Declare consumption and output',
      permissionKey: 'production.declare',
      riskLevel: 'high',
      requiresAudit: true,
      requiresIdempotency: true,
    },
    {
      key: 'production.scrap',
      moduleId: 'production',
      version: '1',
      description: 'Record scrap on declare',
      permissionKey: 'production.scrap',
      riskLevel: 'medium',
      requiresAudit: true,
    },
  ],
  commands: [
    'production.work_order.create',
    'production.work_order.release',
    'production.work_order.declare',
  ],
  queries: ['production.work_orders.list', 'production.work_order.get'],
  permissions: [
    'production.read',
    'production.wo.write',
    'production.declare',
    'production.scrap',
  ],
  dependencies: ['platform', 'organization', 'inventory', 'products'],
  publishedEvents: [
    'production.work_order.created.v1',
    'production.work_order.released.v1',
    'production.consumption.posted.v1',
    'production.output.posted.v1',
    'production.yield.deviation.v1',
    'production.scrap.posted.v1',
  ],
  consumedEvents: [],
  navigationEntries: [
    { id: 'of', label: 'Ordres de fabrication', href: '/production' },
  ],
};
