import type { ModuleManifest } from '../manifest.types';

export const salesManifest: ModuleManifest = {
  id: 'sales',
  name: 'Ventes',
  version: '1.4.0',
  apiVersion: '1',
  description:
    'Sales AUTHORITY — orders + quotes PDF (D318) + returns submodule (D317b) + remises',
  capabilities: [
    {
      key: 'sales.ping',
      moduleId: 'sales',
      version: '1',
      description: 'Sales module liveness surface',
      riskLevel: 'low',
    },
    {
      key: 'sales.read',
      moduleId: 'sales',
      version: '1',
      description: 'List and read sales orders, quotes, and returns',
      permissionKey: 'sales.read',
      riskLevel: 'low',
    },
    {
      key: 'sales.write',
      moduleId: 'sales',
      version: '1',
      description: 'Create/update orders, quotes, and RMAs',
      permissionKey: 'sales.write',
      riskLevel: 'medium',
      requiresAudit: true,
    },
    {
      key: 'sales.confirm',
      moduleId: 'sales',
      version: '1',
      description: 'Confirm order and reserve stock',
      permissionKey: 'sales.confirm',
      riskLevel: 'high',
      requiresAudit: true,
      requiresIdempotency: true,
    },
  ],
  commands: [
    'sales.order.create',
    'sales.order.update',
    'sales.order.confirm',
    'sales.order.cancel',
    'sales.quote.create',
    'sales.quote.update',
    'sales.quote.send',
    'sales.quote.cancel',
    'sales.quote.convert',
    'sales.quote.pdf',
    'sales.quote.publish_portal',
    'sales.return.create',
    'sales.return.post',
    'sales.return.cancel',
    'sales.return.create_credit_note',
    'sales.wa_inbox.match',
    'sales.wa_inbox.dismiss',
    'sales.wa_inbox.draft',
  ],
  queries: [
    'sales.ping',
    'sales.orders.list',
    'sales.orders.get',
    'sales.quotes.list',
    'sales.quotes.get',
    'sales.quotes.pdf',
    'sales.returns.list',
    'sales.returns.get',
    'sales.wa_inbox.list',
    'sales.wa_inbox.get',
  ],
  permissions: ['sales.read', 'sales.write', 'sales.confirm'],
  dependencies: [
    'platform',
    'organization',
    'customers',
    'products',
    'inventory',
  ],
  optionalDependencies: ['master_data'],
  publishedEvents: [
    'sales.order.created.v1',
    'sales.order.confirmed.v1',
    'sales.order.cancelled.v1',
    'sales.quote.created.v1',
    'sales.quote.sent.v1',
    'sales.quote.converted.v1',
    'sales.quote.cancelled.v1',
    'sales.quote.pdf_generated.v1',
    'sales.quote.published_portal.v1',
    'returns.rma.created.v1',
    'returns.rma.posted.v1',
    'returns.rma.cancelled.v1',
    'returns.rma.credit_note_linked.v1',
    'sales.wa_inbox.matched.v1',
    'sales.wa_inbox.dismissed.v1',
    'sales.wa_inbox.draft_created.v1',
  ],
  consumedEvents: [],
  navigationEntries: [
    { id: 'orders', label: 'Commandes', href: '/sales' },
    { id: 'sales-form', label: 'Prise de commande', href: '/sales' },
    { id: 'quotes', label: 'Devis', href: '/sales/quotes' },
    { id: 'returns', label: 'Retours', href: '/sales/returns' },
    { id: 'wa-inbox', label: 'Inbox WhatsApp', href: '/sales/wa-inbox' },
  ],
};
