import type {
  DashboardDefinition,
  WidgetDefinition,
  WidgetInstance,
} from "@/lib/dashboard-engine";
import { globalWidgetRegistry } from "@/lib/dashboard-engine";

const MON = "system_monitoring.view";
const INTEL = "thunder.intel.read";

const refreshField = {
  key: "refreshInterval",
  type: "number" as const,
  label: "Refresh (s)",
  min: 2,
  max: 120,
  default: 5,
};

function def(
  partial: Omit<WidgetDefinition, "version" | "enabled" | "module"> & {
    module?: string;
  },
): WidgetDefinition {
  return {
    version: "1.0.0",
    enabled: true,
    module: partial.module ?? "thunder",
    ...partial,
  };
}

/** Thunder Command Center widget catalog — data from monitor snapshot / intel APIs. */
export const THUNDER_WIDGET_DEFINITIONS: WidgetDefinition[] = [
  def({
    id: "thunder.health",
    code: "THUNDER_HEALTH",
    name: "Thunder Health",
    description: "Matrice santé Core / API / DB / Redis / bus / workers",
    category: "health",
    type: "service-status",
    dataProvider: "thunder.monitor",
    defaultSize: { w: 4, h: 2 },
    minSize: { w: 3, h: 2 },
    maxSize: { w: 6, h: 4 },
    refreshPolicy: "shared-monitor",
    permissions: [MON],
    configurationSchema: { fields: [refreshField] },
  }),
  def({
    id: "thunder.runtime",
    code: "CORE_RUNTIME",
    name: "Core Runtime",
    description: "CPU · RAM · mode · pression",
    category: "runtime",
    type: "gauge",
    dataProvider: "thunder.monitor",
    defaultSize: { w: 4, h: 2 },
    minSize: { w: 3, h: 2 },
    maxSize: { w: 6, h: 3 },
    refreshPolicy: "shared-monitor",
    permissions: [MON],
    configurationSchema: { fields: [refreshField] },
  }),
  def({
    id: "thunder.incidents",
    code: "ACTIVE_INCIDENTS",
    name: "Active Incidents",
    description: "Breakers ouverts · shed · DLQ · fails jobs",
    category: "alerts",
    type: "incident-list",
    dataProvider: "thunder.monitor",
    defaultSize: { w: 4, h: 2 },
    minSize: { w: 3, h: 2 },
    maxSize: { w: 6, h: 3 },
    refreshPolicy: "shared-monitor",
    permissions: [MON],
    configurationSchema: { fields: [refreshField] },
  }),
  def({
    id: "thunder.event-bus",
    code: "EVENT_BUS",
    name: "Event Bus",
    description: "Outbox lag · publish/min · processed",
    category: "events",
    type: "metric-card",
    dataProvider: "thunder.monitor",
    defaultSize: { w: 4, h: 2 },
    minSize: { w: 3, h: 2 },
    maxSize: { w: 6, h: 3 },
    refreshPolicy: "shared-monitor",
    permissions: [MON],
    configurationSchema: { fields: [refreshField] },
  }),
  def({
    id: "thunder.workers",
    code: "WORKERS",
    name: "Workers",
    description: "Families · concurrency · enabled",
    category: "jobs",
    type: "worker-list",
    dataProvider: "thunder.monitor",
    defaultSize: { w: 4, h: 2 },
    minSize: { w: 3, h: 2 },
    maxSize: { w: 6, h: 4 },
    refreshPolicy: "shared-monitor",
    permissions: [MON],
    configurationSchema: { fields: [refreshField] },
  }),
  def({
    id: "thunder.queues",
    code: "QUEUES",
    name: "Queues",
    description: "Pending · running · failed par famille",
    category: "jobs",
    type: "queue-list",
    dataProvider: "thunder.monitor",
    defaultSize: { w: 4, h: 2 },
    minSize: { w: 3, h: 2 },
    maxSize: { w: 6, h: 4 },
    refreshPolicy: "shared-monitor",
    permissions: [MON],
    configurationSchema: { fields: [refreshField] },
  }),
  def({
    id: "thunder.automation-flow",
    code: "AUTOMATION_FLOW",
    name: "Automation Flow",
    description: "Chaîne Order → Worker → Outbox (états dérivés)",
    category: "events",
    type: "flow",
    dataProvider: "thunder.monitor",
    defaultSize: { w: 6, h: 2 },
    minSize: { w: 4, h: 2 },
    maxSize: { w: 12, h: 3 },
    refreshPolicy: "shared-monitor",
    permissions: [MON, INTEL],
    configurationSchema: { fields: [refreshField] },
  }),
  def({
    id: "thunder.throughput",
    code: "EVENT_THROUGHPUT",
    name: "Event Throughput",
    description: "Events/s estimés · publish dernière minute",
    category: "events",
    type: "sparkline",
    dataProvider: "thunder.monitor",
    defaultSize: { w: 6, h: 2 },
    minSize: { w: 4, h: 2 },
    maxSize: { w: 12, h: 3 },
    refreshPolicy: "shared-monitor",
    permissions: [MON],
    configurationSchema: {
      fields: [
        refreshField,
        {
          key: "period",
          type: "select",
          label: "Period",
          options: [
            { value: "5m", label: "5 min" },
            { value: "15m", label: "15 min" },
            { value: "1h", label: "1 h" },
            { value: "24h", label: "24 h" },
          ],
          default: "15m",
        },
      ],
    },
  }),
  def({
    id: "thunder.api",
    code: "API_PERFORMANCE",
    name: "API Performance",
    description: "p95 · admission rejects · job counters",
    category: "performance",
    type: "metric-card",
    dataProvider: "thunder.monitor",
    defaultSize: { w: 4, h: 2 },
    minSize: { w: 3, h: 2 },
    maxSize: { w: 6, h: 3 },
    refreshPolicy: "shared-monitor",
    permissions: [MON],
    configurationSchema: { fields: [refreshField] },
  }),
  def({
    id: "thunder.postgres",
    code: "POSTGRESQL",
    name: "PostgreSQL",
    description: "Connectivité · pool (pas de données métier)",
    category: "system",
    type: "status-card",
    dataProvider: "thunder.monitor",
    defaultSize: { w: 4, h: 2 },
    minSize: { w: 3, h: 2 },
    maxSize: { w: 6, h: 3 },
    refreshPolicy: "shared-monitor",
    permissions: [MON],
    configurationSchema: { fields: [refreshField] },
  }),
  def({
    id: "thunder.redis",
    code: "REDIS",
    name: "Redis",
    description: "OK · mémoire utilisée",
    category: "system",
    type: "status-card",
    dataProvider: "thunder.monitor",
    defaultSize: { w: 4, h: 2 },
    minSize: { w: 3, h: 2 },
    maxSize: { w: 6, h: 3 },
    refreshPolicy: "shared-monitor",
    permissions: [MON],
    configurationSchema: { fields: [refreshField] },
  }),
  def({
    id: "thunder.integrations",
    code: "INTEGRATION_MATRIX",
    name: "Integration Matrix",
    description: "Adapters Thunder (health)",
    category: "integrations",
    type: "integration-matrix",
    dataProvider: "thunder.adapters",
    defaultSize: { w: 4, h: 2 },
    minSize: { w: 3, h: 2 },
    maxSize: { w: 8, h: 4 },
    refreshPolicy: "own",
    permissions: [INTEL],
    configurationSchema: { fields: [refreshField] },
  }),
  def({
    id: "thunder.scheduler",
    code: "SCHEDULER",
    name: "Scheduler",
    description: "Placeholder — jobs planifiés (lot suivant)",
    category: "jobs",
    type: "table",
    dataProvider: "thunder.monitor",
    defaultSize: { w: 4, h: 2 },
    minSize: { w: 3, h: 2 },
    maxSize: { w: 6, h: 3 },
    refreshPolicy: "shared-monitor",
    permissions: [MON],
    configurationSchema: { fields: [refreshField] },
  }),
  def({
    id: "thunder.outbox",
    code: "OUTBOX",
    name: "Outbox",
    description: "Lag · DLQ · latence percentiles",
    category: "events",
    type: "metric-card",
    dataProvider: "thunder.monitor",
    defaultSize: { w: 4, h: 2 },
    minSize: { w: 3, h: 2 },
    maxSize: { w: 6, h: 3 },
    refreshPolicy: "shared-monitor",
    permissions: [MON],
    configurationSchema: { fields: [refreshField] },
  }),
  def({
    id: "thunder.activity",
    code: "ACTIVITY_FEED",
    name: "Activity Feed",
    description: "Signaux Thunder (intel)",
    category: "events",
    type: "event-feed",
    dataProvider: "thunder.signals",
    defaultSize: { w: 4, h: 3 },
    minSize: { w: 3, h: 2 },
    maxSize: { w: 6, h: 5 },
    refreshPolicy: "own",
    permissions: [INTEL],
    configurationSchema: { fields: [refreshField] },
  }),
  def({
    id: "thunder.alerts",
    code: "ALERTS",
    name: "Alerts",
    description: "Seuils configurables (prefs locales V1)",
    category: "alerts",
    type: "alert-list",
    dataProvider: "thunder.alerts",
    defaultSize: { w: 4, h: 3 },
    minSize: { w: 3, h: 2 },
    maxSize: { w: 6, h: 5 },
    refreshPolicy: "shared-monitor",
    permissions: [MON],
    configurationSchema: { fields: [refreshField] },
  }),
  def({
    id: "thunder.resources",
    code: "SYSTEM_RESOURCES",
    name: "System Resources",
    description: "CPU / RAM gauges + jobs",
    category: "runtime",
    type: "gauge",
    dataProvider: "thunder.monitor",
    defaultSize: { w: 4, h: 3 },
    minSize: { w: 3, h: 2 },
    maxSize: { w: 6, h: 4 },
    refreshPolicy: "shared-monitor",
    permissions: [MON],
    configurationSchema: { fields: [refreshField] },
  }),
];

function inst(
  id: string,
  widgetDefinitionId: string,
  order: number,
  x: number,
  y: number,
  w: number,
  h: number,
): WidgetInstance {
  return {
    id,
    widgetDefinitionId,
    dashboardId: "thunder.command-center",
    position: { x, y, w, h },
    configuration: {},
    visibility: true,
    order,
  };
}

/** Default THUNDER CORE COMMAND CENTER layout (12-col desktop). */
export const THUNDER_COMMAND_CENTER: DashboardDefinition = {
  id: "thunder.command-center",
  code: "THUNDER_COMMAND_CENTER",
  name: "Thunder Core Command Center",
  description:
    "Orchestration + monitoring — widgets indépendants · snapshot Thunder",
  module: "thunder",
  scope: "SYSTEM",
  layout: {
    columnsDesktop: 12,
    columnsTablet: 8,
    columnsMobile: 4,
  },
  widgets: [
    inst("i-health", "thunder.health", 0, 0, 0, 4, 2),
    inst("i-runtime", "thunder.runtime", 1, 4, 0, 4, 2),
    inst("i-incidents", "thunder.incidents", 2, 8, 0, 4, 2),
    inst("i-bus", "thunder.event-bus", 3, 0, 2, 4, 2),
    inst("i-workers", "thunder.workers", 4, 4, 2, 4, 2),
    inst("i-queues", "thunder.queues", 5, 8, 2, 4, 2),
    inst("i-flow", "thunder.automation-flow", 6, 0, 4, 6, 2),
    inst("i-tp", "thunder.throughput", 7, 6, 4, 6, 2),
    inst("i-api", "thunder.api", 8, 0, 6, 4, 2),
    inst("i-pg", "thunder.postgres", 9, 4, 6, 4, 2),
    inst("i-redis", "thunder.redis", 10, 8, 6, 4, 2),
    inst("i-int", "thunder.integrations", 11, 0, 8, 4, 2),
    inst("i-sched", "thunder.scheduler", 12, 4, 8, 4, 2),
    inst("i-outbox", "thunder.outbox", 13, 8, 8, 4, 2),
    inst("i-act", "thunder.activity", 14, 0, 10, 4, 3),
    inst("i-alerts", "thunder.alerts", 15, 4, 10, 4, 3),
    inst("i-res", "thunder.resources", 16, 8, 10, 4, 3),
  ],
  permissions: [MON],
  defaultDashboard: true,
  active: true,
};

let registered = false;

export function ensureThunderWidgetsRegistered(): void {
  if (registered) return;
  globalWidgetRegistry.registerMany(THUNDER_WIDGET_DEFINITIONS);
  registered = true;
}
