export const DOCUMENTS_ERROR_CODES = {
  NOT_FOUND: 'DOC.NOT_FOUND',
  LINK_NOT_FOUND: 'DOC.LINK_NOT_FOUND',
  INVALID_LINK: 'DOC.INVALID_LINK',
  STORAGE_UNAVAILABLE: 'DOC.STORAGE_UNAVAILABLE',
  FILE_REQUIRED: 'DOC.FILE_REQUIRED',
  TITLE_REQUIRED: 'DOC.TITLE_REQUIRED',
  INVALID_META: 'DOC.INVALID_META',
} as const;

export type DocumentsErrorCode =
  (typeof DOCUMENTS_ERROR_CODES)[keyof typeof DOCUMENTS_ERROR_CODES];

export const DOCUMENTS_EVENT_TYPES = {
  CREATED: 'documents.document.created.v1',
} as const;
