export const CUSTOMERS_ERROR_CODES = {
  NOT_FOUND: 'CUS.NOT_FOUND',
  CODE_DUP: 'CUS.CODE_DUP',
  PARTY_DUP: 'CUS.PARTY_DUP',
  VERSION_CONFLICT: 'CUS.VERSION_CONFLICT',
  PARTY_NOT_FOUND: 'CUS.PARTY_NOT_FOUND',
  CONTACT_NOT_FOUND: 'CUS.CONTACT_NOT_FOUND',
  ZONE_NOT_FOUND: 'CUS.ZONE_NOT_FOUND',
  ZONE_CODE_DUP: 'CUS.ZONE_CODE_DUP',
  ALREADY_BLOCKED: 'CUS.ALREADY_BLOCKED',
  NOT_BLOCKED: 'CUS.NOT_BLOCKED',
} as const;

export type CustomersErrorCode =
  (typeof CUSTOMERS_ERROR_CODES)[keyof typeof CUSTOMERS_ERROR_CODES];
