export const CUSTOMERS_ERROR_CODES = {
  NOT_FOUND: 'CUS.NOT_FOUND',
  CODE_DUP: 'CUS.CODE_DUP',
  PARTY_DUP: 'CUS.PARTY_DUP',
  VERSION_CONFLICT: 'CUS.VERSION_CONFLICT',
  PARTY_NOT_FOUND: 'CUS.PARTY_NOT_FOUND',
  CONTACT_NOT_FOUND: 'CUS.CONTACT_NOT_FOUND',
  ADDRESS_NOT_FOUND: 'CUS.ADDRESS_NOT_FOUND',
  ZONE_NOT_FOUND: 'CUS.ZONE_NOT_FOUND',
  ZONE_CODE_DUP: 'CUS.ZONE_CODE_DUP',
  ALREADY_BLOCKED: 'CUS.ALREADY_BLOCKED',
  NOT_BLOCKED: 'CUS.NOT_BLOCKED',
  PRICE_INVALID: 'CUS.PRICE_INVALID',
  PRICE_NOT_FOUND: 'CUS.PRICE_NOT_FOUND',
  PRODUCT_NOT_FOUND: 'CUS.PRODUCT_NOT_FOUND',
  INVALID_STATUS: 'CUS.INVALID_STATUS',
  MEMBERSHIP_NOT_FOUND: 'CUS.MEMBERSHIP_NOT_FOUND',
  MEMBERSHIP_DUP: 'CUS.MEMBERSHIP_DUP',
  USER_INVALID: 'CUS.USER_INVALID',
  PORTALS_DISABLED: 'CUS.PORTALS_DISABLED',
  INVALID_ROLE: 'CUS.INVALID_ROLE',
  FISCAL_JUSTIFICATION: 'CUS.FISCAL_JUSTIFICATION',
  FISCAL_INVALID_MODE: 'CUS.FISCAL_INVALID_MODE',
  TAX_CODE_NOT_FOUND: 'CUS.TAX_CODE_NOT_FOUND',
} as const;

export type CustomersErrorCode =
  (typeof CUSTOMERS_ERROR_CODES)[keyof typeof CUSTOMERS_ERROR_CODES];

export const PORTAL_MEMBERSHIP_ROLES = ['buyer', 'viewer', 'admin'] as const;
export type PortalMembershipRole = (typeof PORTAL_MEMBERSHIP_ROLES)[number];

export const CUSTOMERS_EVENT_TYPES = {
  CUSTOMER_CREATED: 'customers.customer.created.v1',
  CUSTOMER_UPDATED: 'customers.customer.updated.v1',
  CUSTOMER_BLOCKED: 'customers.customer.blocked.v1',
  CUSTOMER_UNBLOCKED: 'customers.customer.unblocked.v1',
  CREDIT_CHANGED: 'customers.credit.changed.v1',
  PORTAL_MEMBERSHIP_CHANGED: 'customers.portal_membership.changed.v1',
  FISCAL_UPDATED: 'customers.fiscal.updated.v1',
} as const;

export const FISCAL_OVERRIDE_MODES = [
  'AUTO',
  'ALWAYS',
  'NEVER',
  'CONFIRM',
] as const;

export type FiscalOverrideMode = (typeof FISCAL_OVERRIDE_MODES)[number];

export const FISCAL_NEVER_SOURCES = [
  'EXEMPTION',
  'MANUAL_OVERRIDE',
  'CLIENT_OVERRIDE',
] as const;
