export const PERMISSION_CATALOGUE = [
  'platform.file.read',
  'platform.file.write',
  'platform.search.use',
  'platform.numbering.allocate',
  'identity.self.read',
  'identity.user.manage',
  'identity.session.revoke',
  'org.site.write',
  'license.manage',
  'settings.self',
  'settings.company.write',
  'thunder.job.enqueue',
  'thunder.intel.read',
  'thunder.intel.write',
  'system_monitoring.view',
  'hr.wage.read',
  'hr.employee.read',
  'hr.employee.write',
  'products.read',
  'products.write',
  'products.activate',
  'master_data.refs.read',
  'master_data.party.read',
  'master_data.party.write',
  'customers.read',
  'customers.write',
  'customers.block',
  'customers.credit.set',
  'suppliers.read',
  'suppliers.write',
  'suppliers.hold',
  'fleet.manage',
  'fleet.assign',
  'maintenance.asset',
  'maintenance.wo',
  'inventory.read',
  'inventory.write',
  'inventory.reserve',
  'sales.read',
  'sales.write',
  'sales.confirm',
  'delivery.read',
  'delivery.prepare',
  'delivery.complete',
  'delivery.fail',
  'finance.ar.read',
  'finance.ar.write',
  'finance.allocate',
  'tax.read',
  'tax.rate.manage',
  'documents.read',
  'documents.write',
  'automation.read',
  'automation.write',
  'automation.approve',
  'accounting.read',
  'accounting.write',
  'accounting.post',
  'repair.read',
  'repair.scan',
  'repair.execute',
  'repair.reset',
  'production.read',
  'production.wo.write',
  'production.declare',
  'production.scrap',
  'customer_portal.access',
  'customer_portal.dashboard.read',
  'customer_portal.claims.read',
  'customer_portal.claims.create',
  'customer_portal.documents.read',
  'employee_portal.access',
  'attendance.self',
  'attendance.manage',
  'attendance.approve',
] as const;

export type PermissionKey = (typeof PERMISSION_CATALOGUE)[number];

export const PERMISSION_KEYS = {
  platformFileRead: 'platform.file.read',
  platformFileWrite: 'platform.file.write',
  platformSearchUse: 'platform.search.use',
  platformNumberingAllocate: 'platform.numbering.allocate',
  identitySelfRead: 'identity.self.read',
  identityUserManage: 'identity.user.manage',
  identitySessionRevoke: 'identity.session.revoke',
  orgSiteWrite: 'org.site.write',
  licenseManage: 'license.manage',
  settingsSelf: 'settings.self',
  settingsCompanyWrite: 'settings.company.write',
  thunderJobEnqueue: 'thunder.job.enqueue',
  thunderIntelRead: 'thunder.intel.read',
  thunderIntelWrite: 'thunder.intel.write',
  systemMonitoringView: 'system_monitoring.view',
  hrWageRead: 'hr.wage.read',
  hrEmployeeRead: 'hr.employee.read',
  hrEmployeeWrite: 'hr.employee.write',
  productsRead: 'products.read',
  productsWrite: 'products.write',
  productsActivate: 'products.activate',
  masterDataRefsRead: 'master_data.refs.read',
  masterDataPartyRead: 'master_data.party.read',
  masterDataPartyWrite: 'master_data.party.write',
  customersRead: 'customers.read',
  customersWrite: 'customers.write',
  customersBlock: 'customers.block',
  customersCreditSet: 'customers.credit.set',
  suppliersRead: 'suppliers.read',
  suppliersWrite: 'suppliers.write',
  suppliersHold: 'suppliers.hold',
  fleetManage: 'fleet.manage',
  fleetAssign: 'fleet.assign',
  maintenanceAsset: 'maintenance.asset',
  maintenanceWo: 'maintenance.wo',
  inventoryRead: 'inventory.read',
  inventoryWrite: 'inventory.write',
  inventoryReserve: 'inventory.reserve',
  salesRead: 'sales.read',
  salesWrite: 'sales.write',
  salesConfirm: 'sales.confirm',
  deliveryRead: 'delivery.read',
  deliveryPrepare: 'delivery.prepare',
  deliveryComplete: 'delivery.complete',
  deliveryFail: 'delivery.fail',
  financeArRead: 'finance.ar.read',
  financeArWrite: 'finance.ar.write',
  financeAllocate: 'finance.allocate',
  taxRead: 'tax.read',
  taxRateManage: 'tax.rate.manage',
  documentsRead: 'documents.read',
  documentsWrite: 'documents.write',
  automationRead: 'automation.read',
  automationWrite: 'automation.write',
  automationApprove: 'automation.approve',
  accountingRead: 'accounting.read',
  accountingWrite: 'accounting.write',
  accountingPost: 'accounting.post',
  repairRead: 'repair.read',
  repairScan: 'repair.scan',
  repairExecute: 'repair.execute',
  repairReset: 'repair.reset',
  productionRead: 'production.read',
  productionWoWrite: 'production.wo.write',
  productionDeclare: 'production.declare',
  productionScrap: 'production.scrap',
  customerPortalAccess: 'customer_portal.access',
  customerPortalDashboardRead: 'customer_portal.dashboard.read',
  customerPortalClaimsRead: 'customer_portal.claims.read',
  customerPortalClaimsCreate: 'customer_portal.claims.create',
  customerPortalDocumentsRead: 'customer_portal.documents.read',
  employeePortalAccess: 'employee_portal.access',
  attendanceSelf: 'attendance.self',
  attendanceManage: 'attendance.manage',
  attendanceApprove: 'attendance.approve',
} as const satisfies Record<string, PermissionKey>;

export const PERMISSION_METADATA_KEY = 'authority:permission';

export const PERMISSION_ERROR_CODES = {
  FORBIDDEN: 'IAM.FORBIDDEN',
} as const;

export function isCataloguedPermission(key: string): key is PermissionKey {
  return (PERMISSION_CATALOGUE as readonly string[]).includes(key);
}

export function isWildcardPermission(key: string): boolean {
  return key.includes('*');
}
