export const RETURNS_ERROR_CODES = {
  NOT_FOUND: 'RET.NOT_FOUND',
  INVALID_STATUS: 'RET.INVALID_STATUS',
  VERSION_CONFLICT: 'RET.VERSION_CONFLICT',
  SHIPMENT_NOT_FOUND: 'RET.SHIPMENT_NOT_FOUND',
  SHIPMENT_NOT_DELIVERED: 'RET.SHIPMENT_NOT_DELIVERED',
  ORDER_NOT_FOUND: 'RET.ORDER_NOT_FOUND',
  EMPTY_LINES: 'RET.EMPTY_LINES',
  INVALID_LINE: 'RET.INVALID_LINE',
  QTY_EXCEEDED: 'RET.QTY_EXCEEDED',
  INVOICE_NOT_FOUND: 'RET.INVOICE_NOT_FOUND',
  CREDIT_NOTE_EXISTS: 'RET.CREDIT_NOTE_EXISTS',
} as const;

export type ReturnsErrorCode =
  (typeof RETURNS_ERROR_CODES)[keyof typeof RETURNS_ERROR_CODES];

export const RETURNS_EVENT_TYPES = {
  CREATED: 'returns.rma.created.v1',
  POSTED: 'returns.rma.posted.v1',
  CANCELLED: 'returns.rma.cancelled.v1',
  CREDIT_NOTE_LINKED: 'returns.rma.credit_note_linked.v1',
} as const;

export const RETURNS_RESERVE_REF_TYPE = 'returns.rma';
