export const PRODUCTS_ERROR_CODES = {
  NOT_FOUND: 'PRO.NOT_FOUND',
  SKU_DUP: 'PRO.SKU_DUP',
  VERSION_CONFLICT: 'PRO.VERSION_CONFLICT',
  INVALID_STATUS: 'PRO.INVALID_STATUS',
  REF_UNKNOWN: 'PRO.REF_UNKNOWN',
  FISCAL_JUSTIFICATION: 'PRO.FISCAL_JUSTIFICATION',
  FISCAL_INVALID_MODE: 'PRO.FISCAL_INVALID_MODE',
  TAX_CODE_NOT_FOUND: 'PRO.TAX_CODE_NOT_FOUND',
  TAX_CODE_NOT_VAT: 'PRO.TAX_CODE_NOT_VAT',
} as const;

export type ProductsErrorCode =
  (typeof PRODUCTS_ERROR_CODES)[keyof typeof PRODUCTS_ERROR_CODES];

export const PRODUCTS_EVENT_TYPES = {
  PRODUCT_CREATED: 'products.created.v1',
  PRODUCT_UPDATED: 'products.updated.v1',
  PRODUCT_ACTIVATED: 'products.activated.v1',
  FISCAL_UPDATED: 'products.fiscal.updated.v1',
} as const;

export const PRD_FISCAL_NEVER_SOURCES = [
  'EXEMPTION',
  'MANUAL_OVERRIDE',
  'CLIENT_OVERRIDE',
] as const;
