export const PRODUCTS_ERROR_CODES = {
  NOT_FOUND: 'PRO.NOT_FOUND',
  SKU_DUP: 'PRO.SKU_DUP',
  VERSION_CONFLICT: 'PRO.VERSION_CONFLICT',
  INVALID_STATUS: 'PRO.INVALID_STATUS',
  REF_UNKNOWN: 'PRO.REF_UNKNOWN',
} as const;

export type ProductsErrorCode =
  (typeof PRODUCTS_ERROR_CODES)[keyof typeof PRODUCTS_ERROR_CODES];
